### ISSUE TITLE
Permission denied, rhubab

### ISSUE THREAD

**Issue by Devenoom** [scaredyfish/blender-rhubarb-lipsync#66]
Python: Traceback (most recent call last):
  File "C:\Users\Back\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blender-rhubarb-lipsync\op_blender_rhubarb.py", line 130, in invoke
    self.rhubarb = subprocess.Popen(command,
  File "E:\blender\2.93\2.93\python\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "E:\blender\2.93\2.93\python\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
PermissionError: [WinError 5] Access is denied

location: <unknown location>:-1

How to di fix this, Thank you
![image](https://github.com/user-attachments/assets/ab8215ac-ab32-4afd-9a0d-e872ebb11381)

**Comment by vkyadav123** [comment]
![Image](https://github.com/user-attachments/assets/7cec7e5a-e28c-4b29-9975-4dba29be0613)

![Image](https://github.com/user-attachments/assets/66d7842c-015d-403a-87aa-d6986a937b48)

**Comment by vkyadav123** [comment]
Python: Traceback (most recent call last):
File "C:\Users\Back\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blender-rhubarb-lipsync\op_blender_rhubarb.py", line 130, in invoke
self.rhubarb = subprocess.Popen(command,
File "E:\blender\2.93\2.93\python\lib\subprocess.py", line 951, in init
self._execute_child(args, executable, preexec_fn, close_fds,
File "E:\blender\2.93\2.93\python\lib\subprocess.py", line 1420, in _execute_child
hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
PermissionError: [WinError 5] Access is denied

location: :-1
